[build-system]
requires = [
  "setuptools>=45",
  "setuptools-scm>=6.2",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "simplebot_tgchan/_version.py"

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = "True"
